name: Bug Report
description: Report a bug or issue with the script
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
      placeholder: What should have happened?
    validations:
      required: true
  
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: e.g. macOS 14, Ubuntu 22.04, Windows 11
    validations:
      required: true
  
  - type: input
    id: docker-version
    attributes:
      label: Docker Version
      placeholder: Run 'docker --version'
    validations:
      required: true
  
  - type: input
    id: postgresql-version
    attributes:
      label: PostgreSQL Version
      placeholder: Run 'psql --version'
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true
  
  - type: textarea
    id: error-output
    attributes:
      label: Error output
      description: If there was an error message, paste it here
      render: shell
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context about the problem