name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear description of what you want to happen
      placeholder: Describe the feature...
    validations:
      required: true
  
  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
      description: What problem does this feature solve?
      placeholder: What problem are you trying to solve?
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
      placeholder: How should this feature work?
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions you've considered
      placeholder: What other approaches have you thought about?
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context, screenshots, or examples